# Enable a more feature-rich extra keys row with a DRAWER button
extra-keys = [ \
  ['ESC', 'TAB', 'CTRL', 'ALT', '-', '/', '_', 'UP', 'BKSP'], \
  ['~', '!', '|', '&', '(', ')', 'LEFT', 'DOWN', 'RIGHT', 'DRAWER'] \
]

# Ensure backspace works correctly with Android keyboards
backspace-key = backspace

# Disable the bell character
bell-character = none
