add_newline = true

format = '''
[┌─](bold blue) [Capsd](bold blue) $directory$git_branch
[└─](bold blue)$character'''

[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
disabled = true

[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_branch]
symbol = "󰊢 "
style = "bold purple"
